apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  annotations:
    # k3d 內建 Traefik，entrypoints「web」= 80
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
