name: CD - Build and Push Backend + Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lowercase repo and user
        id: vars
        run: |
          echo "repo_name=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "user_name=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.vars.outputs.user_name }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v4
        with:
          context: backend
          push: true
          tags: ghcr.io/${{ steps.vars.outputs.user_name }}/${{ steps.vars.outputs.repo_name }}-backend:latest

      - name: Build & Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: frontend
          push: true
          tags: ghcr.io/${{ steps.vars.outputs.user_name }}/${{ steps.vars.outputs.repo_name }}-frontend:latest