name: CD - Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract lowercase repo and user
      id: vars
      run: |
        echo "repo_name=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
        echo "user_name=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Log in to GitHub Container Registry (GHCR)
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ steps.vars.outputs.user_name }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ steps.vars.outputs.user_name }}/${{ steps.vars.outputs.repo_name }}:latest .

    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/${{ steps.vars.outputs.user_name }}/${{ steps.vars.outputs.repo_name }}:latest