name: CD - Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry (GHCR)
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

    - name: Extract repo name
      id: repo
      run: |
        REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
        echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT
        
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ steps.repo.outputs.repo_name }}:latest .

    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ steps.repo.outputs.repo_name }}:latest